version: '3.5'

services:

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}

volumes:
  postgresqldata: